version: 2

project_name: shareless

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: shareless
    main: ./cmd/shareless
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

gomod:
  proxy: true

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive
  - id: source 
    artifacts: source

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum
    output: true

dockers_v2:
  - images:
      - "ghcr.io/omurilo/shareless"
      - "omurilo/shareless"
    tags:
      - latest
      - "{{ .Tag }}"
    dockerfile: ./deploy/Dockerfile
    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"
      org.opencontainers.image.description: ""
    annotations:
      "index:org.opencontainers.image.description": ""
    platforms:
      - linux/amd64
      - linux/arm64

docker_signs:
  - cmd: cosign
    output: true
    args:
      - "sign"
      - "${artifact}"
      - "--yes"
