services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./tmp/cache:/data

  shareless:
    image: omurilo/shareless
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

